### ISSUE TITLE
Add Bitcoin Payment Button

### ISSUE THREAD

**Issue by super3** [Storj/bridge-gui#142]
Sorry for my terrible sketch. 

![untitled](https://cloud.githubusercontent.com/assets/60975/24273474/f1e6f73e-0ff8-11e7-8bc4-6ffa2444fd72.png)

**Comment by boshevski** [comment]
![accept-bitcoin](https://cloud.githubusercontent.com/assets/3217669/24307665/40367282-1082-11e7-9a38-fb0db482b207.jpg)

**Comment by super3** [comment]
Also going to need to add a small blurb about it on homepage and the pricing page.
