### ISSUE TITLE
Interface issue when attempting to register the same email twice

### ISSUE THREAD

**Issue by frdwrd** [Storj/bridge-gui#38]
If you attempt to register an email address that belongs to an existing account a warning "Email is already registered" is displayed. However, the user is immediately is redirected to the log-in page, so the warning is never visible to the user. If you click "Sign Up" from the log in page after being redirected, you can view the warning and attempt to register again.

From the user's perspective, she attempts to register, and is redirected to the log-in page with no feedback.

**Comment by bryanchriswhite** [comment]
anyone have any preferences for a TOTP lib?

**Comment by frdwrd** [comment]
Did you mean to comment on #32?

I don't know enough to judge the different libraries. @bookchin?

**Comment by bookchin** [comment]
No preference here, so long as it's free software.

**Comment by bryanchriswhite** [comment]
@frdwrd yea - had too many tabs open... my bad

**Comment by bryanchriswhite** [comment]
for my future reference: https://github.com/Storj/bridge-gui/blob/master/src/utils/apiClient.js#L47 seems to be responsible

**Comment by bryanchriswhite** [comment]
@frdwrd @super3 @bookchin: just a heads up, this issue presents on the password reset form as well. Both symptoms will be resolved when this issue is fixed.

**Comment by barbaraliau** [comment]
Fixed forever ago. By someone.
