### ISSUE TITLE
Better support for password managers

### ISSUE THREAD

**Issue by utdrmac** [Storj/bridge-gui#42]
Latest version of LastPass on Windows 7 Chrome has issues detecting the email and password fields. As such, "Save all entered data" functionality (ie: remember this login) did not work.

**Comment by bookchin** [comment]
I'm not sure if this is the cause, but the password you enter is hashed on the client side before being transmitted (and hashed again before being stored).

**Comment by utdrmac** [comment]
In my case, LastPass didn't recognize the form fields. Maybe they were non-standard HTML or added using JS? I haven't investigated any. I don't think the pre-hashing is an issue.

**Comment by bookchin** [comment]
@MrFancyMonocle might be able to help, the form is rendered client side which could be why

**Comment by super3** [comment]
@utdrmac Is this still happening? I was not able to reproduce.

**Comment by utdrmac** [comment]
LastPass seems to be OK with it now, although the web gui is constantly kicking me out now but that's another issue I guess.

**Comment by super3** [comment]
@utdrmac Yeah, something funky happened with the bridge 4 hours ago. We are looking into it right now. Thanks for your patience.
