### ISSUE TITLE
Create billing interface

### ISSUE THREAD

**Issue by bookchin** [Storj/bridge-gui#5]
More requirements and information will be needed for this

**Comment by bookchin** [comment]
@boshevski when you have some time, can you put something together for @bryanchriswhite to implement?

**Comment by super3** [comment]
@bookchin This is already implemented.

**Comment by super3** [comment]
https://github.com/StorjOld/metadisk.org/blob/master/billing.html

**Comment by dylanlott** [comment]
Here's a quick update of where we're at with the billing platform 

**COMPLETED:**
- Billing page and routes setup in React 
- GraphQL Implementation is completed. 
- React/Apollo set up 

**IN PROGRESS:**
- Working on currency transactions right now and enforcing integer transaction numbers
- Factor out transactions list component in Apollo / React

**UP NEXT:**
- Implement credit card form 
- Add stripe integration 
- Balance calculations and correct billing numbers 

**STRETCH GOALS:**
- E2E testing for everything

**Comment by super3** [comment]
@dylanlott @bryanchriswhite Update?

**Comment by dylanlott** [comment]
@phutchins @super3 @MrFancyMonocle @bookchin 
**Completed**: 
- API endpoints for creating credits and debits 
- Billing logic and checks
- Billing is basically done! Payments can be accepted, debits and credits can be created, and everything tracks a running total of usage and billing. We're just polishing and refactoring, now.

**In Progress**: 
- Test suite for all endpoints and credit/debit logic
- Front end feature polish 

**To Do**: 
- Boot up on a test server with Philip for final round of testing
- Integrate into James' accounting software
- Need to meet with Ryan to link Abacus to Billing via endpoints

**Comment by bookchin** [comment]
Kick ass, nice work d00ds!

**Comment by dylanlott** [comment]
Here's my current status on this right now. Any questions, PM me.

*To Do*:

- Unit tests to ensure accuracy of accounting logic (the big one) 
- Add form validation to credit card form 
- Create a `payment_failure` webhook that Stripe can access (right now, we only handle the `payment_success` webhook)

**Comment by dylanlott** [comment]
Closing this because billing interface is on production

**Comment by dylanlott** [comment]
Closed because Billing is on production
