### ISSUE TITLE
VLC stream issue

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge-gui#81]
command:
storj -k meije0612 stream-file 57af89d533c81c746747945a  57af8d5f9a1e48163c3684d4 | vlc -

error:

C:\WINDOWS\system32>storj -k meije0612 stream-file 57af89d533c81c746747945a  57af8d5f9a1e48163c3684d4 | vlc -
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 108.238.244.144:8603
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

--------------------------------------------------------------------------------------

- After this VLC becomes non-responsive

**Comment by super3** [comment]
@MeijeSibbel We have only tested this in mplayer. Can you try mplayer and see if it produces the same result?

**Comment by MeijeSibbel** [comment]
@super3 : i have tried it but i get no video on my screen, all i get is this:

C:\WINDOWS\system32>storj -k meije0612 stream-file 57af89d533c81c746747945a  57af8d5f9a1e48163c3684d4 | mplayer -
MPlayer Redxii-SVN-r37884-4.9.3 (i686) (C) 2000-2016 MPlayer Team
FFmpeg version: N-81338-g6612d04
Build date: 2016-08-13 18:16:07 EDT

Playing -.
Reading from stdin...
libavformat version 57.46.101 (internal)
Failed to get retrieval token

Exiting... (End of file)

C:\WINDOWS\system32>storj -k meije0612 stream-file 57af89d533c81c746747945a  57af8d5f9a1e48163c3684d4 | mplayer -
MPlayer Redxii-SVN-r37884-4.9.3 (i686) (C) 2000-2016 MPlayer Team
FFmpeg version: N-81338-g6612d04
Build date: 2016-08-13 18:16:07 EDT

Playing -.
Reading from stdin...
libavformat version 57.46.101 (internal)
                                                                                                                                                                                        Failed to get retrieval token

Exiting... (End of file)

C:\WINDOWS\system32>

**Comment by MeijeSibbel** [comment]
I have tried it with the new core on VLC but i get the same error.
