### ISSUE TITLE
Small UX Display Bug

### ISSUE THREAD

**Issue by super3** [Storj/bridge-gui#95]
![fireshot capture 35 - - https___app storj io_ _dashboard_billing__k mqapv1](https://cloud.githubusercontent.com/assets/60975/22377246/2009e2f2-e47f-11e6-9250-7372060825de.png)

**Comment by bryanchriswhite** [comment]
@super3 care to elaborate a bit on what the actual issue here is plz?

**Comment by boshevski** [comment]
Just add class "form-control" on the country <select> and it will be fixed.

**Comment by bryanchriswhite** [comment]
@boshevski that plus a bunch of `form-group`s, minus a bunch of validation error divs

@boshevski @super3 is this satisfy?
![screenflow](https://cloud.githubusercontent.com/assets/600733/22565033/072c62a2-e987-11e6-86dd-e3a1f908944c.gif)

**Comment by bryanchriswhite** [comment]
will open a PR soon...

**Comment by boshevski** [comment]
@bryanchriswhite that's great, it just needs a little empty space before Credit Card Details

**Comment by bryanchriswhite** [comment]
@boshevski I didn't add the space before card details cos i'm not sure what's the correct way to do that. Would you mind? - you can PR against my master branch which, when merged will append to this PR.
